# Bonus Homework 4

In this homework we will write a Naive Bayes classifier under the assumption that features  are Exponentially distributed real numbers. 

You will need to use the results that you derived on problem 2 of the written homework

### Imports

In [1]:
import numpy as np

### Random Seed

In [2]:
seed=48593
np.random.seed(seed)

### Helper functions

In [3]:
def exponential_mixture(N,pi,intensities):
        D,K=intensities.shape
        Z=np.random.multinomial(1,pi,N)
        obs=np.random.exponential(1/intensities.ravel(),(N,D*K))
        obs=obs.reshape(N,D,K)
        X=np.sum(Z[:,np.newaxis,:]*obs,axis=2)
        X.shape
        Y=Z.argmax(axis=1)
        return X,Y

In [4]:
def one_hot_encode(Y):
    K=np.max(Y)+1
    N=len(Y)
    Z=np.zeros((N,K))
    Z[np.arange(N),Y]=1
    return Z

## Problem

<div class="alert alert-block alert-success"> Problem 0.0 </div>
We generate samples for  Exponential Mixture Model

In [5]:
N=2000

In [6]:
pi0=np.array([0.25,0.5,0.25])


In [7]:
# lambda is a reserved word in python
intensities0=np.array([
                        [0.05,1,40],
                        [0.5,1,2],
                        [1,1,1],
                        [2,1,0.5],
                        [40,1,0.05]
    ])
intensities0.shape,intensities0.dtype

((5, 3), dtype('float64'))

In [8]:
X,Y=exponential_mixture(N,pi0,intensities0)
X_test,Y_test=exponential_mixture(N,pi0,intensities0)
X.shape,Y.shape

((2000, 5), (2000,))

## Problems

<div class="alert alert-block alert-info"> Problem 1.0 </div>
How may classes $K$ can the labels $Y$ take?
How may dimension $D$ has the feature vector X?

In [9]:
K=len(np.unique(Y))
D=X.shape[1]
print("K =",K)
print("D =",D)

K = 3
D = 5


<div class="alert alert-block alert-info"> Problem 1.1 </div>
Estimate, based on the sample data, the marginal probabilites of the possible Y values $p(y=k)$

In [10]:
Z=one_hot_encode(Y)
N_hat=Z.sum(axis=0)
pi_hat=N_hat/N
pi_hat

array([0.2475, 0.4865, 0.266 ])

<div class="alert alert-block alert-info"> Problem 1.2 </div>
Estimate the Poisson parameters  $\hat{\lambda}_{d,k}$ for the distribution of $x_d$ conditional on $y=k$

In [11]:
lambda_hat=N_hat/ np.sum(X[:,:,np.newaxis]*Z[:,np.newaxis,:],axis=0)
lambda_hat

array([[ 0.05373118,  0.93518722, 39.57929162],
       [ 0.51139355,  0.98002395,  1.99960325],
       [ 1.01456651,  0.99439333,  0.94768629],
       [ 1.86820894,  0.95230844,  0.51080887],
       [41.45809243,  1.03320135,  0.05110256]])

<div class="alert alert-block alert-info"> Problem 1.3 </div>
As you showed on the written homework
$$
    p(y=k|X)=\frac{ e^{\sum_d X_{i,d} W_{d,k} + b_k}}{\sum_{k'} e^{\sum_d X_{i,d}W_{d,k'}+b_{k'}}}
$$
Compute $W$ and $b$

In [12]:
W=-lambda_hat
W

array([[ -0.05373118,  -0.93518722, -39.57929162],
       [ -0.51139355,  -0.98002395,  -1.99960325],
       [ -1.01456651,  -0.99439333,  -0.94768629],
       [ -1.86820894,  -0.95230844,  -0.51080887],
       [-41.45809243,  -1.03320135,  -0.05110256]])

In [13]:
b=np.log(pi_hat)+np.log(lambda_hat).sum(axis=0)
b

array([-0.62659752, -0.82953184, -0.65241642])

<div class="alert alert-block alert-info"> Problem 1.4 </div>
Find the predicted class  $\hat{Y}$ given the parameters $W$ and $b$ for the training data $X$


In [14]:
eta=np.dot(X,W)+b
Y_pred=eta.argmax(axis=1) # the normalization term is the same for all classes, so it can be ignored

<div class="alert alert-block alert-info"> Problem 1.5 </div>
Compute the average in sample accuracy

In [15]:
np.mean(Y_pred==Y)

0.957

<div class="alert alert-block alert-info"> Problem 1.6 </div>
Compute the accuracy of the fitted model on the test data `X_test`, `Y_test`

In [16]:
eta=np.dot(X_test,W)+b
Y_pred=eta.argmax(axis=1)
np.mean(Y_pred==Y_test)

0.9575

<div class="alert alert-block alert-info"> Problem 2.1 </div>
Create a classifier class by filling in the `fit` and `predict` methods on the class below

In [17]:
class ExponentialNB:
    def __init__(self):
        pass
    def fit(self,X,Y):
        pass
    def predict(self,X):
        pass

In [18]:
class ExponentialNB:
    def __init__(self):
        pass
    def fit(self,X,Y):
        N=len(X)
        Z=one_hot_encode(Y)
        N_hat=Z.sum(axis=0)
        pi_hat=N_hat/N
        lambda_hat= N_hat/np.sum(X[:,:,np.newaxis]*Z[:,np.newaxis,:],axis=0)
        print(lambda_hat)
        self.W=-lambda_hat
        self.b=np.log(pi_hat)+np.log(lambda_hat).sum(axis=0)
    def predict(self,X):
        eta=np.dot(X,self.W)+self.b
        return eta.argmax(axis=1)

<div class="alert alert-block alert-info"> Problem 2.2 </div>
Fit model to the training data `X1`, `Y1` below, 
compute the model accuracy on the training set

In [19]:
# lambda is a reserved word in python
pi1=[0.4,0.1,0.1,0.4]
intensities1=np.array([
                        [1000., 0.001,   1 ,0.001],
                        [0.001 ,0.001,    1,1000],             
    ])

In [20]:
X1,Y1=exponential_mixture(100000,pi1,intensities1)
X1_test,Y1_test=exponential_mixture(100000,pi1,intensities1)
X1.shape,Y1.shape

((100000, 2), (100000,))

In [21]:
model=ExponentialNB()
model.fit(X1,Y1)
Y1_pred=model.predict(X1)
print(Y1_pred)
np.mean(Y1_pred==Y1)

[[1.01990200e+03 9.98947933e-04 9.96273502e-01 1.00463137e-03]
 [9.98187632e-04 1.01462341e-03 9.88704857e-01 1.00965339e+03]]
[0 0 3 ... 2 1 0]


0.99936

<div class="alert alert-block alert-info"> Problem 2.3 </div>
Compute the model accuracy of the model  on the test data `X1_test`,`Y1_test`

In [22]:
Y1_pred=model.predict(X1_test)
np.mean(Y1_pred==Y1_test)

0.99928

In [23]:
X[:10]

array([[2.07762634e-02, 2.38064235e+00, 4.97791098e-01, 4.20192185e-01,
        1.21056240e+00],
       [9.86773709e-02, 1.76334112e-01, 1.98248963e+00, 2.56168477e+00,
        8.39929325e-01],
       [5.65187628e+00, 8.19640324e+00, 4.38275591e-01, 9.03611927e-01,
        2.75551048e-02],
       [6.85432340e+00, 5.81195064e-01, 2.72571222e+00, 1.76332537e+00,
        2.11279675e+00],
       [1.20930031e-02, 1.62125802e-02, 2.36661005e+00, 3.42185915e-01,
        2.47821346e+01],
       [5.35356941e-03, 1.24623223e-01, 7.51514481e-01, 1.25588521e+00,
        1.67330184e+01],
       [3.82135703e-03, 8.00777037e-01, 3.01361382e-01, 1.64748208e-01,
        7.95740876e+00],
       [1.27153986e-02, 1.78447686e-01, 9.65621416e-01, 1.07590945e+00,
        2.07962505e+01],
       [6.68721884e-01, 1.09776348e-01, 2.54486187e+00, 7.31463475e-01,
        5.66301176e-01],
       [9.93190696e-02, 1.06745530e+00, 1.42114784e+00, 7.59135429e-01,
        8.28521153e-01]])